hz: 10
goal_dist_th: 0.4
goal_yaw_th: 0.16
predict_dt: 0.1
predict_time: 3.0
velocity_reso: 0.02
yawrate_reso: 0.05

heading_score_gain: 1.0
approaching_score_gain: 3.0

robot_radius: 0.5
max_speed: 0.3
min_speed: -0.2
max_yawrate: 2.0
max_accel: 10.0
max_dyawrate: 6.0

odom_topic_name: /odom
